id: IE6857569
ocr_import_info:
  timestamp: '2023-09-28T02:50:19.433594+00:00'
  batch_id: batch-1fd1
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 03:20:56.528512+00:00
last_modified: 2023-09-28 03:20:56.528519+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W22938
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22938
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མའི་རྟགས་རིགས་པའི་སྐོར་གཏན་ལ་འབེབས་པར་བྱེད་པ་སྡེ་བདུན་སྒོ་བརྒྱ་འབྱེད་པའི་འཕྲུལ་གྱི་ལྡེའུ་མིག
  languages:
  - bo
  author: ངོར་པ་དཔོན་སློབ་བློ་གཏེར་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.975053636407781
  ocr_word_median_confidence_index: 0.99943566
bases:
  I3645:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3645
      total_pages: 498
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3645.txt
    statistics:
      ocr_word_median_confidence_index: 0.99943566
      ocr_word_mean_confidence_index: 0.975053636407781
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
